[general]
bars = 50
sleep_timer = 5
[input]
[output]
method = sdl_glsl
bar_delimiter = 0
sdl_width = 150
sdl_height = 39
vertex_shader = pass_through.vert
fragment_shader = bar_spectrum.frag
continuous_rendering = 1;
[color]
background = '#282C34'
gradient = 1
gradient_count = 2
gradient_color_1 = '#282C34'
gradient_color_2 = '#45475A'
[smoothing]
[eq]