[general]
bars = 48
sleep_timer = 5

[input]
method = pipewire
source = auto

[output]
method = sdl_glsl
sdl_width = 300
sdl_height = 20
continuous_rendering = 1
vertex_shader = pass_through.vert
fragment_shader = bar_spectrum.frag

[color]
background = '#000000'
foreground = '#ffffff'
gradient = 1
gradient_count = 4
gradient_color_1 = '#00ff88'
gradient_color_2 = '#ffcc00'
gradient_color_3 = '#ff6600'
gradient_color_4 = '#ff0066'
